name: stitch
channel_priority: strict  # Only look in conda-forge when not available in defaults.
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - jupyter
  - seaborn
  - tqdm
  - pytest
  - scipy
  - tabulate
  - torchtnt  # only for FLOP counts in the analysis notebooks
  - wandb  # optional
  - pip:
      - torch
      - torchvision
      - pyyaml-include  # optional
      - timm  # optional
